version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/nestdb

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    ports:
      - "3001:3001"
    environment:
      - BOT_TOKEN=5821534037:AAGGxevje9-Qlf4PSh6TeIjPWFiEWzrrXC0
      - WEB_APP_URL=https://your-web-app-url.com
    volumes:
      - ./bot:/bot
      - /bot/node_modules

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  db_data:
