version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    env_file:
      - ./.env

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./bot:/bot
      - /bot/node_modules
    env_file:
      - ./.env

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - ./.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env

volumes:
  db_data:
